
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app-of-apps
    name: in-cluster
  project: default
  source:
    path: apps
    repoURL: https://github.com/pankajbapat/pankajargocdtest
    targetRevision: HEAD
